name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check PHP version
      run: php -v
    - name: Check PHP extension
      run: php -m
    - name: Check PHP ini
      run: php --ini
