name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Check PHP version
      run: php -v
    - name: Check PHP extensions
      run: php -m
    - name: Check PHP ini
      run: php --ini
    - name: Check Composer
      run: composer --version
    - name: Check Composer cache
      run: composer config -g cache-dir
