name: CI
#on: gollum
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
        fail-fast: false
    steps:
    - uses: actions/checkout@v1

    - name: Check PHP version
      run: php -v

    - name: Check PHP extensions
      run: php -m

    - name: Check PHP ini
      run: php --ini

    - name: Check Composer
      run: composer --version
      if: matrix.os == 'ubuntu-latest'

    - name: Check Composer location
      run: which composer
      if: matrix.os == 'ubuntu-latest'

    #- name: Check Composer can update
    #  run: composer self-update 1.9.0 --verbose
    #  if: matrix.os == 'ubuntu-latest'

    #- name: Check Composer cache location with cmd
    #  run: echo %LOCALAPPDATA%\Composer
    #  if: matrix.os == 'windows-latest'
    #  shell: cmd

    #- name: Check Composer cache location
    #  run: echo -$env:LOCALAPPDATA\Composer
    #  if: matrix.os == 'windows-latest'

    - name: Check Composer cache
      run: composer config -g cache-dir
      if: matrix.os == 'ubuntu-latest'

    - name: Show HOME location
      run: echo $HOME

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    #- name: Disable tls
    #  run: composer config -g disable-tls true

    #- name: Composer update
    #  run: composer self-update

    - name: Composer diagnose
      run: composer diagnose
