name: CI
#on: gollum
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Check PHP version
      run: php -v
    - name: Check PHP extensions
      run: php -m
    - name: Check PHP ini
      run: php --ini
    - name: Check Composer
      run: composer --version
      if: matrix.os == 'ubuntu-latest'
    - name: Check Composer cache location
      run: echo %LOCALAPPDATA%\Composer
      shell: cmd
      if: matrix.os == 'windows-latest'
    - name: Check Composer cache
      run: composer config -g cache-dir
      if: matrix.os == 'ubuntu-latest'
    - name: Show HOME location
      run: echo $HOME
