name: Matrix
on: gollum
#on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 15
      matrix:
        operating-system: [windows-latest]
        php-versions: ['7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get installed PHP location
      id: php-location
      run: echo "::set-output name=dir::$PHPROOT"
      shell: bash

    - name: Get installed PHP version
      id: php-version
      run: echo "::set-output name=ver::$(php -r 'echo PHP_VERSION."-".PHP_ZTS;')"
      shell: bash

    - name: Restore cached php version
      id: php-cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.php-location.outputs.dir }}
        key: ${{ matrix.php-versions }}-php-${{ steps.php-version.outputs.ver }}

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: mbstring, xdebug #optional, setup extensions
        #ini-values-csv: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
        #coverage: xdebug #optional, setup coverage driver
        #pecl: true #optional, setup PECL
      #if: steps.php-cache.outputs.cache-hit != 'true'

    - name: Report versions
      run: |
        php -v
        composer --version --ansi

    - name: Check PHP Version
      run: php -v

    - name: Check PHP binary
      run: php -r "echo PHP_BINARY, PHP_EOL;"

    - name: Check env PHPROOT
      run: echo $env:PHPROOT

    - name: Check Composer Version
      run: composer -V

    - name: Check PHP Extensions
      run: php -m
