name: Matrix
on: push
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 15
      matrix:
        operating-system: [windows-latest]
        php-versions: ['5.5', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: none

    - name: Check PHP Version
      run: php -v

    - name: Check PHP binary
      run: php -r "echo PHP_BINARY, PHP_EOL;"

    - name: Check env PHPROOT
      run: echo $env:PHPROOT

    - name: Check ini
      run: php --ini

    - name: Check PHP Extensions
      run: php -m
