name: Native PHP
on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
        fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Check PHP version
      run: php -v

    - name: Check PHP extensions
      run: php -m

    - name: Check PHP ini
      run: php --ini

    - name: Check Composer
      run: composer --version

    - name: Check Composer location
      run: which composer
      #if: matrix.os == 'ubuntu-latest'

    - name: Check Composer cache
      run: composer config -g cache-dir

    - name: Show HOME location
      run: echo $HOME

    # Older stuff used for testing bits and bobs
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '5.5.3'

    #- name: Disable tls
    #  run: composer config -g disable-tls true

    #- name: Composer update
    #  run: composer self-update

    - name: Composer diagnose
      run: composer diagnose
      shell: bash

    - name: Require something
      run: composer require composer/xdebug-handler --no-interaction --no-progress --prefer-dist
      shell: bash

    #- name: Exit code should be 42 - shell bash
    #  run: php -r "exit(42);"
    #  shell: bash

    #- name: Exit code should be 42 - shell pwsh
    #  run: php -r "exit(42);"
    #  shell: pwsh
    #  if: always()
